# Generated by Django 2.2.2 on 2019-06-27 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assetlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assetname', models.CharField(max_length=50)),
                ('controlno', models.CharField(max_length=50)),
                ('modelno', models.CharField(max_length=50)),
                ('boughtdate', models.DateField()),
                ('stockplace', models.CharField(max_length=50)),
            ],
        ),
    ]
